version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ApexLegendsRanking-cron"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-b50fa4nr27u0"
s3_prefix = "ApexLegendsRanking-cron"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "RoleName=\"ApexLegendsRankingCron\""
